project: 
  type: website
  output-dir: docs/
website:
  favicon: /images/logo.png
  open-graph: true
  page-navigation: true  
  title: "Außerschulische Lernorte"
  site-url: https://OGERhub.github.io/aslo
  repo-url: https://github.com/OGERhub/aslo
  search: 
    location: navbar
    type: textbox
  # page-footer: 
  #   center: "[OGERhub (2024)](https://github.com/OGERhub/) | [Impressum](../unit00/impressum.html)"
  twitter-card:
    creator: "@gisma"
  comments: false
   # utterances:
   #   repo: OGERhub/aslo
  navbar:
    logo: /images/logo.png
    # left:
    #   - icon: question-square-fill
    #     text: FAQ
    #     href: unit00/unit00-faq.qmd
    #   - icon: check2-square

  sidebar:
    # logo: /images/logo.jpg
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:
      - section: "HowTo AsLo"
        contents:
          - index.qmd
          - unit00/unit00-02-stupruef.qmd
          - unit99/pruefung.qmd
          
      - text: "---"   
      - section: "Ausserschulische Lernorte"
        contents: 
          - href: unit99/tag-1.qmd
            text: "Folien Blocktag 1"      
          - href: unit99/tag-2.qmd
            text: "Folien Blocktag 2"    
          - href: unit99/tag-3.qmd
            text: "Folien Blocktag 3"           
          - href: unit01/unit01-01.qmd
            text: "Begriffsklärung und Grundlagen"
          - href: unit01/unit01-02.qmd
            text: "Didaktische Konzepte"            
          - href: unit99/expose.qmd
            text: "Anleitung Exposé"     
      - text: "---"
      - section: "Ressourcen"
        contents:
          - href: unit02/unit02-01.qmd
            text: "TaskCards"
          - href: unit02/unit02-02.qmd
            text: Quarto Markdown
          - href: unit02/unit02-03.qmd
            text: "AsLo Template"            
      # - text: "---"
      # - section: "AsLo Projekte"
      #   contents:


      #- text: "---"
      #- section: "Machine Learning"
      #  contents:
      #    - Machine_Learning_Session/ML_AOA.qmd
          # - href: https://gisma-courses.github.io/LV-uav-workflow/modules/module-introduction/
          #   text: Basic Readings        
          # - href: https://gisma-courses.github.io/LV-uav-workflow/modules/module-fieldwork/
          #   text: uav/Flight Planning
      - text: "---"
##format: dokuwiki

execute:
  freeze: auto
format: 
  html: 
      include-after-body: ../css/banner-footer.html
      include-in-header: ../css/banner-style.html
      code-overflow: wrap
      toc-title: "Inhalt"
      number-sections: false
      highlight-style: github
      theme:
       light: cerulean #css/html-inrae.css
       dark: [lumen, css/theme-dark.scss]
      # code-background: true
      code-copy: true
      css: css/styles.css
      toc: true
      link-external-icon: false
      link-external-newwindow: true
      link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
# filters:
#   - include-files.lua
#   - quarto
