project: 
  type: website
  output-dir: docs/

website:
  title: "Außerschulische Lernorte"
  site-url: https://OGERhub.github.io/aslo
  repo-url: https://github.com/OGERhub/aslo
  repo-actions: [edit]
  favicon: /images/logo.png
  bread-crumbs: false
  open-graph: true
  page-navigation: true
  comments: false

  twitter-card:
    creator: "@gisma"

  search: 
    location: navbar
    type: textbox

  navbar:
    logo: /images/logo.png

  sidebar:
    pinned: true
    align: center
    style: docked
    collapse-level: 1
    contents:
      - section: "HowTo AsLo"
        contents:
          - index.qmd
          - unit00/unit00-02-stupruef.qmd

      - text: "---"

      - section: "Außerschulische Lernorte"
        contents: 
          - href: unit99/tag-1.qmd
            text: "Folien Blocktag 1"
          - href: unit99/tag-2.qmd
            text: "Folien Blocktag 2"
          - href: unit99/tag-3.qmd
            text: "Folien Blocktag 3"
          - href: unit01/unit01-05.qmd
            text: "Kompetenzmodell zur Bewertung"
          - href: unit01/unit01-06.qmd
            text: "Themenfelder zur Klimaresilienz"
          - href: unit01/unit01-02.qmd
            text: "Didaktische Konzepte"            

            

      - text: "---"

      - section: "Ressourcen"
        contents:
          - href: unit01/unit01-07.qmd
            text: "Quiz zur Klimaresilienz"
          - href: unit02/unit02-01.qmd
            text: "TaskCards"
          - href: unit02/unit02-08.qmd
            text: "Warm Up Exkursionsreflexion "            
#          - href: unit02/unit02-02.qmd
#            text: "Quarto Markdown"
#          - href: unit02/unit02-03.qmd
#            text: "AsLo Template"

      - text: "---"

format:
  html: 
    theme: 
      light: cerulean
      dark: [lumen, css/theme-dark.scss]
    css: css/styles.css
    code-overflow: wrap
    code-copy: true
    toc: true
    toc-title: "Inhalt"
    number-sections: false
    highlight-style: github
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
    include-after-body: css/banner-footer.html
    include-in-header: css/banner-style.html

execute:
  freeze: auto
