---
title: "Lerntagebuch"
title-block-banner: ../images/learnjournal-header.png
title-block-banner-color: black

---

Grundlage für Reflexion am Mittwochmorgen (bzgl. Lerntagebuch)
Wie haben die Beobachtungen während der Exkursion gezeigt, wie der Klimawandel unsere lokale Umgebung beeinflussen? Wo vulnerabel/ wo resilient?
Wie sichtbar ist der Klimawandel am Lernort? 
Wie erfahrbar war die Vulnerabilität / Resilienz des Lernortes?
Wie schätzen Sie die zukünftige Vulnerabilität ein? Wie besorgt sind Sie über die weitere Entwicklung der Vulnerabilität des besuchten Lernortes?
Wie viel Hoffnung haben Sie, dass der Lernort in der Zukunft resilienter wird?
Inwiefern sind die Adaptionen zukunftsfähig? 
Wie weitreichend ist die betrachtete Adaption? 

Vorgehen:
Kategorien von Lernorten ableiten (auf Basis der Ideenskizzen -> Mittwochmorgen besprechen) 
Z.B.: Resilienz erfahren / Vulnerabilität erfahren / Veränderungen sehen 
Dann jeweils für die abgeleiteten Kategorien jeweils 1 Template (z.B. auf Ilias) erstellen und die obigen Fragen daran anpassen 

Weitere: (mögliche)
Welche Kompetenzen werden durch die Exkursion gefördert? (z.B. DGfG?)
Grad der Sensibilisierung: (1-10 z.B.) (umformulieren!) 
Exkursionsdidaktische Aspekte / Feedback auf Skala 
	- 