%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#E98585',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#7C0000',
      'lineColor': '#F8B229',
      'secondaryColor': '#57CD52',
      'tertiaryColor': '#D42118'
    }
  }
}%%

mindmap
  root((Außerschulische <br> Lernorte)) 
    id1(positive Aspekte)
      ::icon(fa  fa-plus)
      Entlastung und Öffnung des Schulunterrichts
      Lebenswelt und Wissenschaftsbezug
      Regionale Identität und erlebte Sachlichkeit
      Primärerfahrungen
      Fachliche Orientierung und Verbindung mit authentischen Kontexten
    negative Aspekte
    ::icon(fa   fa-minus)
      Gefahr kognitiver Überforderung
      Planungsaufwand
    ambivalente Aspekte
      ::icon(fa  fa-ellipsis-h  ) 
      Experten Laien Kommunikation

%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#E98585',
      'primaryTextColor': '#fff',
      'primaryBorderColor': '#7C0000',
      'lineColor': '#F8B229',
      'secondaryColor': '#57CD52',
      'tertiaryColor': '#D42118'
    }
  }
}%%

mindmap
    root((Integration von Expertenwissen in Lernumgebungen))
    %% Chancen Branch
       Chancen
          Bereicherung des Lernsettings
          Einbringung spezifischen Fachwissens
          Erweiterung der Lerninhalte
          Erhöhung der Authentizität
          Expertennähe zur Wissenschaft, Handwerk etc.
          Praxisnahe Lernerfahrungen

    %% Herausforderungen Branch
     Herausforderungen
       Abstimmungsprobleme
       Unterschiedliche berufliche/fachliche Hintergründe
       Koordinationsaufwand
       Wissensasymmetrien
       Erschwerte Kommunikation
       Wahrnehmung von Machtasymmetrie

    %% Kommunikationsbarrieren Branch
     Kommunikationsbarrieren
        Zielgruppengerechte Vermittlung
        Variable Fähigkeit, Wissen anzupassen
        Zögern der Laien, Fragen zu stellen
