---
title: "Prüfungsleistung"
title-block-banner: ../images/publish-header.png
title-block-banner-color: black
---

## Vorbemerkung

Im Rahmen der Prüfungsleistung sollen Sie Ihren AsLo für einen Oberstufenkurs nutzbar machen. Dazu sollen Sie nicht die Durchführung Ihres AsLo im Rahmen des Seminars verschriftlichen, sondern den Lernort auf der Grundlage Ihrer Seminarerfahrungen für den schulischen Einsatz in der Oberstufe mit entsprechender Vor- und Nachbereitung konzipieren. Bitte bedenken Sie auch bei der Umsetzung für die Schule, dass es zu den Zielen von AsLo gehört, klare Bildungsziele für außerschulische Lernorte zu entwickeln, d.h. Ziele, die nicht ebenso gut oder besser im Klassenzimmer erreicht werden können, was zwingend die Fähigkeit erfordert, geeignete Lernorte zu identifizieren und die Lernenden zu aktivieren. Die Themenwahl sollte die eigenen Stärken und Interessen berücksichtigen. 

Sie können Ihren Beitrag entweder als Word-Dokument oder als Markdown-Dokument einreichen (in beiden Fällen bitte im Ilias-Ordner). Wenn Sie Ihren Beitrag in Markdown einreichen, werden wir ihn auf dieser Homepage veröffentlichen, um eine konkrete Nutzung zu ermöglichen. Unter [Ressourcen](../unit02/unit02-02.qmd) finden Sie eine Vorlage, die Sie verwenden können, wenn Ihr Beitrag veröffentlicht werden soll und Sie gleichzeitig Ihre digitalen Kompetenzen weiterentwickeln möchten.

## Der Praxisbeitrag


Der Praxisbeitrag soll die Lehrkräfte in die Lage versetzen, ihr AsLo-Konzept unter den gegebenen räumlichen Bedingungen möglichst reibungslos in die schulische Praxis umzusetzen. Er soll wie das Exposé die Motivation, die Fragestellung und die Ziele auf der Basis des aktuellen Forschungsstandes und der vor Ort vorhandenen Ressourcen darstellen. Die konkrete Umsetzung des außerschulischen Lernortes einschließlich der notwendigen Vor- und Nachbereitung ist für einen Oberstufenkurs zu konzipieren und mit unterstützenden Materialien zu versehen. Dazu sind die konkreten Lernorte in Marburg zu benennen und die Materialien an die örtlichen Gegebenheiten anzupassen. Digitale Materialien können verlinkt werden. Im Text sollte auf das Material verwiesen werden, um zu verdeutlichen, wie das Material eingesetzt werden soll. Achten Sie bei der Konzeption Ihres Lernortes auf eine angemessene Aktivierung der Schüler*innen.


::: {.callout-important appearance="simple" title="Formalia" icon="false"}
-   maximal 3000 Worte / \~ 9 Seiten
-   Upload in Ihren PG-Ordner auf Marvin-Ilias bis zum 30.09.2024 um 23.55 Uhr als:
    - PDF: *Name_Name_Name_3.pdf*
    - Markdown: *Name_Name_Name_3.zip*
    
     Die QMD-Datei besteht in der Regel aus der Markdown-Datei und den eingebetteten Grafiken, die sinnvollerweise in einem Ordner namens `images` gespeichert werden. Der Ordner und die QMD-Datei müssen dann gezippt als Archiv eingereicht werden. 
:::

## Beispieltemplate

Sie finden unter dem Menupunkt [Ressourcen->Template](../unit02/unit02-03.qmd) eine Strukturvorlage für Ihre Arbeit. Sollten Sie die Arbeit für eine Online-Stellung ausführen wollen können Sie gerne den Menupunkt [Ressourcen->Quarto Markdown](../unit02/unit02-02.qmd) nutzen.
