---
title: "Reflexion Exkursion und Poster"


title-block-banner: ../images/taskcard-header.png
title-block-banner-color: black

format: html

---

## "Warm Up Exkursionsreflexion

Diese Befragung ergänzt das Lerntagebuch, das die Exkursionen Ihrer Kolleg:innen dokumentiert, um eine strukturierte Reflexion Ihrer eigenen Exkursion.

Ziel ist es, zentrale Aspekte Ihrer Erfahrung systematisch zu erfassen und für die weitere Arbeit im Seminar nutzbar zu machen.

Die Befragung dient:

- der Aktivierung Ihrer Erinnerung an prägende Situationen
- der gezielten Selbstreflexion anhand raumtheoretischer und didaktischer Kategorien
- der verdichteten, vergleichbaren Darstellung gruppenübergreifender Exkursionserfahrungen
- sowie der qualitativen und quantitativen Auswertung im wissenschaftlichen Kontext

Ihre Angaben bilden zugleich eine Grundlage für Ihre Posterarbeit und tragen zur Weiterentwicklung des Lehrformats bei.


[Befragung Reflexion Gruppe Reudenbach](https://forms.gle/2rJRkX8XpNR1GDKx6)

[Befragung Reflexion Gruppe Ammoneit](https://forms.gle/a6d6X4k9TRgxTXh8A)



