on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install stringr + detect and install used R packages
        run: |
          Rscript -e 'install.packages("stringr", repos="https://cloud.r-project.org")'
          Rscript -e '
            used_packages <- unique(stringr::str_match_all(
              paste(readLines(list.files(pattern = "\\\\.qmd$", recursive = TRUE)), collapse = "\n"),
              "library\\(([\\"\\\']?)([[:alnum:]\\.]+)\\1\\)"
            )[[1]][,3])
            if (length(used_packages) > 0) {
              install.packages(used_packages, repos = "https://cloud.r-project.org")
            } else {
              message("No R packages detected.")
            }
          '

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
